### ISSUE TITLE
How did you add an "activate the extension" hotkey on page manipulator?

### ISSUE THREAD

**Issue by fishsticks89** [Ruud14/Ruud14#1]
I checked your manifest, but it doesn't seem to include the hotkey. How did you do it?

**Comment by Ruud14** [comment]
What exactly do you mean with an 'activate the extension' hotkey?

**Comment by fishsticks89** [comment]
![Uploading image.png…]()

**Comment by fishsticks89** [comment]
![image](https://user-images.githubusercontent.com/61331006/118174874-394a0600-b3e4-11eb-9779-d346ef555a87.png)

**Comment by Ruud14** [comment]
I don't remember adding that as a feature. Are you sure that isn't default?

**Comment by Ruud14** [comment]
Hmm... I see that not all my chrome extensions have an option to add a hotkey... Guess it's not a default feature.

**Comment by fishsticks89** [comment]
it is, sorry

**Comment by fishsticks89** [comment]
it just doesn't appear if you load unpacked
