### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pedrinho1709** [Ruud14/Ruud14#2]
Hello Ruud, greetings from Brazil! I'm sending this message because I have several doubts and some issues while using your extension, "Page Manipulator." I'm not very knowledgeable in computer science as my course is focused on agribusiness. I would like to know if there's a possibility that you could assist me in modifying some elements on a website using your extension, as I haven't found any tutorials online. It would be amazing, and I appreciate your help in advance. Thank you!
[Screenshot_20230621-103803_OneDrive.pdf](https://github.com/Ruud14/Ruud14/files/12090759/Screenshot_20230621-103803_OneDrive.pdf)

**Comment by Ruud14** [comment]
Hi pedrinho,

Please start by checking out the [examples](https://github.com/Ruud14/Page-Manipulator/tree/master/examples) and reading [the questions others have asked](https://github.com/Ruud14/Page-Manipulator/issues?q=is%3Aissue+is%3Aclosed). I am sure those can help you with the basics.

If  that does not help you, please provide more info about your specific  use case. Your screenshot seems to be from a pdf and not a webpage. The extension is not able to modify pdfs.

**Comment by pedrinho1709** [comment]
in my case, i just want to change a little text in a page, is - to MM, and
i dont know how i use the code in page manipulator

Em qua., 19 de jul. de 2023 às 15:24, Ruud Brouwers <
***@***.***> escreveu:

**Comment by Ruud14** [comment]
Please have a look at [this comment](https://github.com/Ruud14/Page-Manipulator/issues/30#issuecomment-1360929383) that I wrote and the links that it refers to.

**Comment by pedrinho1709** [comment]
Good morning Ruud, I still haven't been able to solve that doubt of mine,
and I really tried, I would like to know if there is a possibility for you
to do this for me, then I'll send you the url of the site along with the
login and password, I'll also send you a few dollars for the inconvenience,
or if you can help me via discord.

Em qui., 20 de jul. de 2023 13:34, Ruud Brouwers ***@***.***>
escreveu:

**Comment by Ruud14** [comment]
Feel free to mail me the details and I'll see what I can do :)

**Comment by pedrinho1709** [comment]
Thanks, I will.

Site url:
https://autenticacao.unb.br/sso-server/login?service=https%3A%2F%2Fsig.unb.br%2Fsigaa%2Flogin%2Fcas

Login: 211052092

Password: pedrinhoagro1709

You Will need to go in "ensino" and go to "consultar minhas notas" then you
change the "-" to "MM" in "faltas" you put "2" and in "situação" you put
"APROVADO" i will send you The prints

Em dom., 23 de jul. de 2023 13:16, Ruud Brouwers ***@***.***>
escreveu:

**Comment by pedrinho1709** [comment]
hi ruud, You did it?

Em dom., 23 de jul. de 2023 às 15:59, Pedro ***@***.***>
escreveu:

**Comment by Ruud14** [comment]
For the first step:
1. Create a JavaScript file within the extension.
2. Put https://sigaa.unb.br/sigaa/portais/discente/discente.jsf in the 'active websites' box.
3. Set 'matching pages' to recursive.
4. Check the 'active' checkbox
5. Put this code in the editor:

```javascript
// Find all td elements with class name 'situacao'
const tdElements = document.querySelectorAll("td.situacao");
// Find the correct one. (trial and error resulted in 3)
const tdElement = tdElements[3]
tdElement.innerHTML = "MM";
```

**Comment by pedrinho1709** [comment]
Thanks, I'll check it out.

Em qua., 26 de jul. de 2023 11:50, Ruud Brouwers ***@***.***>
escreveu:

**Comment by Ruud14** [comment]
Sorry, here is the full script:
```javascript

// Find all td elements with class name 'situacao'
const tdElements = document.querySelectorAll("td.situacao");
// Find the correct one. (trial and error resulted in these indexes)
tdElements[1].innerHTML = "APROVADO";
tdElements[3].innerHTML = "2";


const tdElementsWithHyphen = Array.from(document.querySelectorAll("td")).filter(tdElement => tdElement.innerHTML.includes("-"));
tdElementsWithHyphen[2].innerHTML = "MM";
```

**Comment by pedrinho1709** [comment]
hi ruud, can you change all this, to stay like

MM          MM             0            APROVADO

Em qua., 26 de jul. de 2023 às 12:10, Ruud Brouwers <
***@***.***> escreveu:

**Comment by pedrinho1709** [comment]
hi ruud, can you change this elements to stay like

MM      MM    0    APROVADO

Em qua., 26 de jul. de 2023 às 12:10, Ruud Brouwers <
***@***.***> escreveu:

**Comment by pedrinho1709** [comment]
you will save my life haha


Em qua., 26 de jul. de 2023 às 12:20, Pedro ***@***.***>
escreveu:

**Comment by pedrinho1709** [comment]
You can do it please?

Em qua., 26 de jul. de 2023 12:24, Pedro ***@***.***> escreveu:

**Comment by Ruud14** [comment]
Here you go, this changes the other '--'s as well:
```javascript
// Find all td elements with class name 'situacao'
const tdElements = document.querySelectorAll("td.situacao");
// Find the correct one. (trial and error resulted in these indexes)
tdElements[1].innerHTML = "APROVADO";
tdElements[3].innerHTML = "2";
tdElements[4].innerHTML = "APROVADO";


const tdElementsWithHyphen = Array.from(document.querySelectorAll("td")).filter(tdElement => tdElement.innerHTML.includes("-"));
tdElementsWithHyphen[2].innerHTML = "MM";
tdElementsWithHyphen[3].innerHTML = "MM";
tdElementsWithHyphen[4].innerHTML = "MM";
tdElementsWithHyphen[5].innerHTML = "MM";
```

**Comment by pedrinho1709** [comment]
worked in part  ruud, but I want element II to be MM too. and situação
fundamentos de ciencia do solo to aprovado

Em qua., 26 de jul. de 2023 às 12:47, Ruud Brouwers <
***@***.***> escreveu:

**Comment by pedrinho1709** [comment]
thanks again for the help you is awsome

Em qua., 26 de jul. de 2023 às 13:16, Pedro ***@***.***>
escreveu:

**Comment by pedrinho1709** [comment]
theres a example how i want these things [image: Capturar.PNGTTTT.PNG]

Em qua., 26 de jul. de 2023 às 13:16, Pedro ***@***.***>
escreveu:

**Comment by pedrinho1709** [comment]
here, i changed in inspect element, want to stay like this

Em qua., 26 de jul. de 2023 às 13:21, Pedro ***@***.***>
escreveu:

**Comment by pedrinho1709** [comment]
Hi my friend you still here?

Em qua., 26 de jul. de 2023 13:24, Pedro ***@***.***> escreveu:
